import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#241a00",
        "inverse-primary": "#006d37",
        "surface-variant": "#343535",
        "surface-container-low": "#1b1c1c",
        "surface-container-highest": "#343535",
        "secondary-container": "#4a4949",
        "surface": "#121414",
        "primary-fixed": "#34d399",
        "tertiary-container": "#ffdb79",
        "on-primary-fixed": "#052e16",
        "on-tertiary-fixed-variant": "#584400",
        "on-error": "#690005",
        "error-container": "#93000a",
        "outline": "#849585",
        "tertiary-fixed": "#ffe08d",
        "on-secondary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#005228",
        "primary-fixed-dim": "#16a34a",
        "surface-bright": "#383939",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#c8c6c5",
        "secondary-fixed": "#e5e2e1",
        "tertiary": "#fffaf7",
        "surface-container-high": "#292a2a",
        "surface-container": "#1f2020",
        "on-primary-container": "#007139",
        "on-primary": "#003919",
        "inverse-on-surface": "#303031",
        "on-background": "#e3e2e2",
        "surface-tint": "#16a34a",
        "on-surface": "#e3e2e2",
        "primary": "#f1ffef",
        "primary-container": "#22c55e",
        "inverse-surface": "#e3e2e2",
        "secondary": "#c8c6c5",
        "surface-container-lowest": "#0d0e0f",
        "background": "#0a0a0a", // Exact custom token background
        "on-secondary": "#313030",
        "tertiary-fixed-dim": "#e5c364",
        "surface-dim": "#121414",
        "on-surface-variant": "#b9cbb9",
        "on-secondary-fixed-variant": "#474646",
        "error": "#ffb4ab",
        "on-tertiary": "#3d2f00",
        "on-tertiary-container": "#795f01",
        "on-secondary-container": "#bab8b7",
        "outline-variant": "#3b4b3d",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "gutter": "24px",
        "container-max": "1200px",
        "section-gap": "80px",
        "margin-mobile": "16px",
        "unit": "8px",
        "margin-desktop": "40px",
      },
      fontFamily: {
        "headline-lg-mobile": ["var(--font-inter)"],
        "metric-lg": ["var(--font-jetbrains-mono)"],
        "body-md": ["var(--font-inter)"],
        "headline-lg": ["var(--font-inter)"],
        "code-md": ["var(--font-jetbrains-mono)"],
        "label-sm": ["var(--font-jetbrains-mono)"],
        "headline-xl": ["var(--font-inter)"],
      },
    },
  },
  plugins: [],
};

export default config;
